language: c
sudo: required
  
before_install:
  - sudo apt-get build-dep -y octave
  
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

os:
  - linux
  - osx
  
script: asdf plugin-test octave https://github.com/nverno/asdf-octave.git
